# Generated by Django 6.0.6 on 2026-07-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_price', models.BigIntegerField()),
                ('Product_description', models.TextField()),
                ('Product_stock', models.BigIntegerField()),
                ('Product_image', models.ImageField(upload_to='product_image')),
            ],
        ),
    ]
