# Generated by Django 6.0.6 on 2026-07-24 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekartapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekartapp.register')),
            ],
        ),
    ]
