# Generated by Django 6.0.6 on 2026-07-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=20)),
            ],
        ),
    ]
