# Generated by Django 6.0.6 on 2026-07-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ekartapp.category'),
            preserve_default=False,
        ),
    ]
