# Generated by Django 6.0.7 on 2026-07-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0004_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='Product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ekartapp.category'),
            preserve_default=False,
        ),
    ]
