# Generated by Django 6.0.6 on 2026-07-29 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0005_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekartapp.category'),
        ),
    ]
