# Generated by Django 6.0.6 on 2026-08-04 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0006_alter_products_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('address', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekartapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekartapp.register')),
            ],
        ),
    ]
