# Generated by Django 5.2.16 on 2026-08-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0006_orders'),
        ('ekartapp', '0007_orders'),
    ]

    operations = [
    ]
